test_all:
  image: base/devel
  stage: build
  script:
    - pacman --noconfirm -Syu ocaml ocaml-findlib opam
    - opam init --disable-sandboxing -y
    - opam switch create -y 4.06.0
    - eval `opam config env`
    - opam install -y camlp4 ocamlfind ocamlbuild batteries
    - pacman --noconfirm -Syu bazel
    - pacman --noconfirm -Syu git
    - bazel test //:all
